export const PRODUCT_REQUEST="PRODUCT_REQUEST";
export const PRODUCT_FAILURE="PRODUCT_FAILURE";
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS";

////////////////////////////ADDRESSS

export const ADDRESS_REQUEST="ADDRESS_REQUEST";
export const ADDRESS_FAILURE="ADDRESS_FAILURE";
export const ADDRESS_SUCCESS="ADDRESS_SUCCESS"