export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_FAILURE="LOGIN_FAILURE";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS";
export const USER_REQUEST="USER_REQUEST";
export const USER_FAILURE="USER_FAILURE";
export const USER_SUCCESS="USER_SUCCESS";

export const ADMIN_SUCCESS="ADMIN_SUCCESS"

export const DELETE_ITEM="DELETE_ITEM";
export const ADD_ITEM="ADD_ITEM";
export const LOGOUT ="LOGOUT";
export {}